<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <RootNamespace>Social.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Primitives\Common.Primitives.csproj" />
    <ProjectReference Include="..\Models\Domain.Models.csproj" />
  </ItemGroup>
</Project>
